//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeShare.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int banner_id { get; set; }
        public string banner_title { get; set; }
        public string banner_image { get; set; }
        public string banner_link { get; set; }
        public Nullable<System.DateTime> banner_datecreate { get; set; }
        public Nullable<bool> banner_active { get; set; }
    }
}
