//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeShare.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int chat_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string chat_content { get; set; }
        public Nullable<System.DateTime> chat_datecreate { get; set; }
    }
}
