//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeShare.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Code()
        {
            this.Comments = new HashSet<Comment>();
            this.Groups = new HashSet<Group>();
            this.Orders = new HashSet<Order>();
            this.Tools = new HashSet<Tool>();
        }
    
        public int code_id { get; set; }
        public string code_title { get; set; }
        public Nullable<int> code_coin { get; set; }
        public string code_code { get; set; }
        public string code_des { get; set; }
        public string code_info { get; set; }
        public string code_setting { get; set; }
        public Nullable<int> code_view { get; set; }
        public Nullable<int> code_viewdown { get; set; }
        public string code_linkdemo { get; set; }
        public string code_linkdown { get; set; }
        public Nullable<System.DateTime> code_datecreate { get; set; }
        public Nullable<System.DateTime> code_dateupdate { get; set; }
        public Nullable<int> code_active { get; set; }
        public Nullable<bool> code_option { get; set; }
        public Nullable<bool> code_del { get; set; }
        public string code_tag { get; set; }
        public Nullable<int> code_disk { get; set; }
        public string code_pass { get; set; }
        public Nullable<int> user_id { get; set; }
        public string code_img { get; set; }
        public Nullable<int> category_id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tool> Tools { get; set; }
        public virtual Category Category1 { get; set; }
    }
}
