//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeShare.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int news_id { get; set; }
        public string news_name { get; set; }
        public Nullable<int> news_view { get; set; }
        public string news_content { get; set; }
        public string news_tag { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> news_datecreate { get; set; }
        public Nullable<System.DateTime> news_dateupdate { get; set; }
        public Nullable<int> news_active { get; set; }
        public Nullable<bool> news_option { get; set; }
        public Nullable<bool> news_del { get; set; }
        public string news_img { get; set; }
    
        public virtual User User { get; set; }
    }
}
