//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeShare.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int rating_id { get; set; }
        public Nullable<int> rating_sum { get; set; }
        public Nullable<System.DateTime> rating_datecreate { get; set; }
        public string rating_content { get; set; }
        public Nullable<int> rating_cl { get; set; }
        public Nullable<int> rating_dmrr { get; set; }
        public Nullable<int> rating_run { get; set; }
        public Nullable<bool> rating_like { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> code_id { get; set; }
    
        public virtual Code Code { get; set; }
        public virtual User User { get; set; }
    }
}
