//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeShare.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rep
    {
        public int rep_id { get; set; }
        public Nullable<int> comment_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string rep_content { get; set; }
        public Nullable<System.DateTime> rep_datecreate { get; set; }
        public Nullable<System.DateTime> rep_dateupdate { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual User User { get; set; }
    }
}
