//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeShare.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        public int tool_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> code_id { get; set; }
        public Nullable<int> news_id { get; set; }
        public Nullable<System.DateTime> tool_datecreate { get; set; }
        public Nullable<bool> tool_item { get; set; }
    
        public virtual Code Code { get; set; }
        public virtual User User { get; set; }
    }
}
